version: "3.1"

services:
  aca:
    image: ghcr.io/nsacyber/hirs/aca:alpha1
    container_name: aca
    ports:
       - 8443:8443
  hat:
    image: ghcr.io/nsacyber/hirs/hat:alpha1
    container_name: hat
    ports:
       - 67:67/udp
       - 68:68/udp
       - 69:69
       - 80:80
    networks:
      hat_network:
        ipv4_address: 172.16.1.3
         
networks:
  hat_network:
    driver: transparent
    name: hat_network
    ipam:
      config:
        - subnet: 172.16.1.0/24
          gateway: 172.16.1.1