# This workflow will RIM tests
name: RIM Tests
on:
  push:
    branches:
      - '*v3*'
      - 'main'
  workflow_dispatch:
env:
  TEST_STATUS: 0
jobs:
  DockerTests:
    runs-on: ubuntu-latest
    outputs:
      test-result: ${{ steps.set_outputs.outputs.test-result }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: RIM Tests Setup
        continue-on-error: true
        shell: bash
        run: |
          # If on a forked repo, ensure that it has a new secret for the PAT
          # and replace secrets.GITHUB_TOKEN with the secret in the fork
          echo ${{ secrets.SUI }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          .ci/system-tests/setup_system_tests.sh ${GITHUB_REF#refs/heads/}
      - name: Primary_rim_create_pass - Initial Rim Test
        continue-on-error: true
        shell: bash
        run: |
          .ci/tcg-rim-tool/scripts/primary_rim_create_pass.sh
      - name: Check System Test results
        if: success() || failure()
        run: |
          if [ ${TEST_STATUS} == "0" ]; then
            exit 0;
          else
            exit 1;
          fi