# This workflow will RIM tests
name: RIM Tests
on:
  push:
    branches:
      - '*v3*'
      - 'main'
  workflow_dispatch:
env:
  TEST_STATUS: 0
jobs:
  DockerTests:
    runs-on: ubuntu-latest
    outputs:
      test-result: ${{ steps.set_outputs.outputs.test-result }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build RIM Tool
        run: |
          pwd
          ls
          cd tools/tcg_rim_tool
          pwd
          ls
          sudo ./gradlew clean Build
          sudo ./gradlew buildDeb
          ls
          sudo dpkg -i /build/distributions/tcg-rim-tool*.deb
      - name: Primary_rim_create_pass - Initial Rim Test
        continue-on-error: true
        shell: bash
        run: |
          .ci/tcg-rim-tool/scripts/primary_rim_create_pass.sh
      - name: Check System Test results
        if: success() || failure()
        run: |
          if [ ${TEST_STATUS} == "0" ]; then
            exit 0;
          else
            exit 1;
          fi
